set nocompatible
set number
set autoindent
set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4
set shiftround
set nowrap
set noswapfile

set backspace=indent,eol,start
set hidden
set laststatus=2
set display=lastline

set showmode
set showcmd

set incsearch
set hlsearch

set ttyfast
set lazyredraw

set splitbelow
set splitright

set wrapscan
set report=0
set synmaxcol=200

colorscheme 256-jungle
