
colorscheme 256-jungle

set nocompatible
set number
set autoindent
set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4
set shiftround
set nowrap
set noswapfile

set backspace=indent,eol,start
set hidden
set laststatus=2
set display=lastline

set showmode
set showcmd

set incsearch
set hlsearch

set ttyfast
set lazyredraw

set splitbelow
set splitright

set wrapscan
set report=0
set synmaxcol=200

" netrw, the builtin file explorer
" Press <Ctrl+e> to access netrw browser
" in a new tab, press <Enter> to open it
let g:netrw_browse_split=0
let g:netrw_winsize = 25
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_altv = 1
map <C-E> :tabnew <bar> :Explore<CR>
